### ISSUE TITLE
symbolic_sims.csv is missing

### ISSUE THREAD

**Issue by H4CK3R-01** [dunder-1/cbr-system#1]
Hello!

I am working on a project and would like to implement a Case Based Reasoning algorithm.
I found your repository and want to test it, but the symbolic_sims.csv file is missing. I found the used_cars_flat.csv file on the website.
Can you provide the missing file? Thank you

**Comment by dunder-1** [comment]
Hey,

thanks for reaching out! I uploaded the symbolic_sims.csv into the data folder. Notice that the values are arbitrary and basically my own biased view on similarity between car models.

**Comment by H4CK3R-01** [comment]
Thank you very much. I think that helps to understand the algorithm
